### ISSUE TITLE
Breaks with horizontal lines if there's no metadata

### ISSUE THREAD

**Issue by raine** [jxson/front-matter#21]
Something like below will break `front-matter`. It thinks the content between the horizontal lines is metadata.

```md
# hello world

this is a markdown document

---

some text here

---

foo
```

This can be avoided by declaring an empty metadata, but maybe a proper fix is to only look for metadata in the beginning of the file.

```md
---
---

etc
```

**Comment by jxson** [comment]
Agreed on only looking at the beginning of the file, I believe this is a regression. I can take a look in the next day or so...

**Comment by raine** [comment]
Thank you.

**Comment by raine** [comment]
Any luck with this?

**Comment by jxson** [comment]
Hey @raine sorry for the delay, just got back from vacation. I am looking at this and a few other changes that should be made as well, will have an update soon.
