### ISSUE TITLE
Use js-yaml over yaml-js

### ISSUE THREAD

**Issue by devinus** [jxson/front-matter#25]
https://github.com/nodeca/js-yaml is more maintained and faster.

**Comment by jxson** [comment]
Thanks for the suggestion @devinus I will look into it swapping it out. Any idea of the test suite is as thorough?

This is kind of related to #22, it would be nice to be able to pass in your own parser as an option (even if it is just a different yaml parser).

**Comment by slang800** [comment]
:+1:
