### ISSUE TITLE
Merging with dsfm

### ISSUE THREAD

**Issue by axdg** [jxson/front-matter#34]
@jxson I've written [dsfm](https://github.com/axdg/dsfm) for parsing strings containing front-matter of whatever type.

Looking through your issues, I see that you've been planning to implement custom parsers and stream support. dsfm has both of these, and the API is mostly borrowed from [d3's csv/tsv parser](https://github.com/d3/d3-dsv) which is the best that I've been able to find for a module that allows you to implement custom parsers, but also has defaults parsers (yaml and json in this case).

Also, there is some performance improvement; see [this gist](https://gist.github.com/axdg/526229a65b050b7ef2dc), those are benchmark results from [here](https://github.com/axdg/node-front-matter-benchmark) and [here](https://github.com/axdg/gray-matter). In either case clone the repo, `npm install` and `npm run benchmark` to test them yourself.

I wonder how you'd feel about maybe merging the two modules, given that you have the best name on npm and that I don't feel the need to maintain a seperate module if yours will eventually implement the same API? maybe into v3.0.0 of front-matter (but I could also extend the API of front-matter 2.x.x). 

If your up for this, let me know and I'll start a branch on your repo and start making pull requests.

Cheers

**Comment by jxson** [comment]
@axdg Thanks for the message, I am open to merging the two.

I have some minor nits about API design etc. we should jump on a hangout to work that out and plan a strategy.

I had a couple of things mulling around my head that I haven't gotten down into issues or anything, at a high level the only big thing is ditching regex and running with a similar pattern to [fuzzysearch](https://github.com/bevacqua/fuzzysearch) and [balanced-match](https://github.com/juliangruber/balanced-match) provided the benchmarks show it's faster which I have a feeling it will be and the code will end up being simpler and easier to maintain.

I'll shoot you an email so we can schedule a time to chat.

If anyone else wants to join just comment on this thread and we can include you.

**Comment by axdg** [comment]
Sounds good, let me know. And keep in mind that I'm in Sydney - so maybe somewhere around 6:00pm your time, on whichever day, would be best.

**Comment by axdg** [comment]
Closing this now
