### ISSUE TITLE
systems using front-matter?

### ISSUE THREAD

**Issue by klml** [jxson/front-matter#43]
Is there a overview of systems using the front matter format?

Beside jeykll I found:

* [metalsmith](http://www.metalsmith.io/#how-does-it-work-)
* [middleman](https://middlemanapp.com/basics/frontmatter/)

**Comment by jxson** [comment]
Hi @klml 

I haven't been keeping track but there are a lot: https://www.npmjs.com/browse/depended/front-matter

If you think this would be helpful feel free to open a PR that adds a section for popular dependants to the README.md 💃
