### ISSUE TITLE
Multiline blocks of text in front-matter

### ISSUE THREAD

**Issue by alidcastano** [jxson/front-matter#50]
Does this accept large blocks of text?

For example:

```
description: |
   This is a really long description so
   it needs two lines

```

I couldn't get the above example to work. Is there another way to do it? Couldn't find an example in docs or tests. Thanks

**Comment by jxson** [comment]
Valid YAML should work, there might be a regression in the YAML parser (or it might need to be updated).

If you add a failing test in a PR I'll chase it down.

**Comment by alidcastano** [comment]
Ah, you're right, this does work. The error was somewhere else!
